#!/usr/bin/env python3

import argparse
import sys


if __name__ != "__main__":
    raise Exception("Whatcha doin")


parser = argparse.ArgumentParser(
    description="Add the same indent to each line of stdin")
parser.add_argument("infile", type=str, default="-", nargs="?",
                    help="Input filename. Default is stdin, also - means stdin")
parser.add_argument("-n", "--number",
                    type=int,
                    default=1,
                    help=(
                        "Number of repetitions of the indent symbol to add. "
                        "Default: 1"
                    ))
parser.add_argument("-s", "--symbol",
                    type=str,
                    default=" ",
                    help=(
                        "Symbol to prepend to each line as an 'indent'. "
                        "Default: A single space character."
                    ))
ARGV = parser.parse_args()


def open_infile():
    if ARGV.infile == "-":
        return sys.stdin
    return open(ARGV.infile, "r")


with open_infile() as infile:
    for line in infile:
        print(ARGV.symbol * ARGV.number + line, end="")
