#!/usr/bin/env python

from string import ascii_uppercase as ABC
from string import ascii_lowercase as abc
import argparse
from sys import stdout

def caesar(text, shift): # shift is the number to shift the text.
    res = ''
    for i in range(len(text)):
        c = text[i]
        if c in ABC:
            res += ABC[(shift + ABC.find(c)) % 26]
        elif c in abc:
            res += abc[(shift + abc.find(c)) % 26]
        else:
            res += c # for, like, spaces and stuff
    return res

def main():
    parser = argparse.ArgumentParser(description='Apply a Caesar cipher like '
                                     'rot13. Ignores non-alphabet characters.')
    parser.add_argument('infile', type=argparse.FileType('r'),
                        help='Input file. - for stdin.')
    parser.add_argument('-k', '--key', type=int, default=13,
                        help='Distance to shift the input. For example, '
                        'a value of three will change "A" to "D". '
                        'Default 13.')
    args = parser.parse_args()
    stdout.write(caesar(args.infile.read(), args.key))

if __name__ == '__main__':
    main()
